### ISSUE TITLE
为什么指定D盘Python.exe

### ISSUE THREAD

**Issue by blazeqin** [yangchong211/YCWalleHelper#1]
仔细看过每个文件，没有发现指定路径的代码，D:\Python\YCWalleHelper\venv\Scripts\Python.exe，因为我的文件在E盘，Python也没装在D盘。。。请问楼主怎么修改?

**Comment by yangchong211** [comment]
第一种原因分析：这是因为Windows会根据一个Path的环境变量设定的路径去查找python.exe，如果没找到，就会报错。如果在安装时漏掉了勾选Add python.exe to Path，那就要手动把python.exe所在的路径【你电脑安装到了那个路径】添加到Path中。
第二种原因分析：依次操作file—>Settings—>Project Interpreter—>修改python.exe路径【你的路径】，我的同事和同行已经校验过该项目，方案是可行的。看到你的这个问题，我自己操作了一边，希望可以解决你这个问题。
截图如下所示
![image](https://upload-images.jianshu.io/upload_images/4432347-91394d67b6b7ffef.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![image](https://upload-images.jianshu.io/upload_images/4432347-7da00b85082a287f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![image](https://upload-images.jianshu.io/upload_images/4432347-094c2cf8220a7967.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
